### ISSUE TITLE
Add test case

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-os-rename#1]
we need a test case that runs on windows.

@gatesvp

**Comment by jbenet** [comment]
ping @gatesvp could you add a test case for this repo?

**Comment by gatesvp** [comment]
Will do. Top of my list for the weekend :)

**Comment by gatesvp** [comment]
FYI, this test works verbatim against the Linux version, obviously just needs a different file name. Though given the complexity of the Linux version, I'm not sure how much it matters, given that it will fail elsewhere.

**Comment by jbenet** [comment]
Closed in 01a8da4 and 3ac97f6
